### ISSUE TITLE
Dead link to 'meccano'

### ISSUE THREAD

**Issue by dmitrizagidulin** [solid/solid-platform#1]
The [meccano](https://github.com/Qatar-Computing-Research-Institute/qcri-crosscloudP/tree/meccano) link in the Servers list does not seem to be working (as in, that Github repo gives a 404 Not Found).

Has it moved somewhere, or does it need to be removed?

**Comment by csarven** [comment]
Currently private. Ping @mansoure

**Comment by dmitrizagidulin** [comment]
@mansoure - Should we keep that link on the servers list?

**Comment by dmitrizagidulin** [comment]
Ok, well, no worries. Handled in https://github.com/solid/solid-platform/pull/2, closing.
